version: "3"

services:
  hd-site:
    build: .
    hostname: hd
    env_file:
      - ./web/.env
    ports:
      - 8080:8080
      - 6001:6001
    volumes:
      - ./web:/var/www/html
    restart: on-failure:3
    depends_on:
    - hd-db
    - hd-memcached
    - hd-redis

  hd-db:
    #    image: registry.wayatech.se/frontend/hd/db
    build: db
    hostname: hd-db
    env_file:
      - ./web/.env
    ports:
      - ${HOST_AUX_PORT_HEKTO:-10}81:5432
    restart: on-failure:3

  hd-memcached:
    image: memcached:latest
    hostname: hd-memcached
    env_file:
    - ./web/.env
    restart: on-failure:3

  hd-redis:
    image: redis:latest
    hostname: hd-redis
    env_file:
      - ./web/.env
    restart: on-failure:3

networks:
  default:
    external:
      name: ${NETWORK:-local2}
