version: "3"

services:
  hd-site:
    build: web
    hostname: hd
    env_file:
      - web/.env
    ports:
      - 80:80
    volumes:
      - ./web/dist:/usr/share/nginx/html
      - ../media:/usr/share/nginx/html/img/years
    restart: on-failure:3

networks:
  default:
    external:
      name: ${NETWORK:-local}
