/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: E6qgOynrR71+1QnDGvlepZ5UY8ihEDWtenx1zLmAfogaTj8pU9pVUCscp8jWvB3jkn34bpuXZPoH6XwSjVDMJA==
 */

// eslint:disable
// tslint:disable

interface Accounts {
  /**
   * @default false
   */
  active: boolean
  balance: number
  created_at: (Date) | null
  /**
   * @default nextval('accounts_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'accounts_id'}
  inactive_since: (Date) | null
  name: string
  password: string
  /**
   * @default true
   */
  print: boolean
  uid: string
  updated_at: (Date) | null
}
export default Accounts;

interface Accounts_InsertParameters {
  /**
   * @default false
   */
  active?: boolean
  balance: number
  created_at?: (Date) | null
  /**
   * @default nextval('accounts_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'accounts_id'}
  inactive_since?: (Date) | null
  name: string
  password: string
  /**
   * @default true
   */
  print?: boolean
  uid: string
  updated_at?: (Date) | null
}
export type {Accounts_InsertParameters}
