/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 72lRefidYBfCoKVV5JkPS84XO9X8rcGleFQMyHA951B+ugW9xCGzHHZznlCklnwt/fMy+/+V/fQQPCD8j3LTlA==
 */

// eslint:disable
// tslint:disable

import Products from './products'

interface Barcodes {
  barcode: string
  created_at: (Date) | null
  /**
   * @default nextval('barcodes_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'barcodes_id'}
  product_id: Products['id']
  updated_at: (Date) | null
  variant_name: (string) | null
}
export default Barcodes;

interface Barcodes_InsertParameters {
  barcode: string
  created_at?: (Date) | null
  /**
   * @default nextval('barcodes_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'barcodes_id'}
  product_id: Products['id']
  updated_at?: (Date) | null
  variant_name?: (string) | null
}
export type {Barcodes_InsertParameters}
