/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: A1J/pZWPjCjcReojfrbnCeD8UYjGDlVv7MaalZGHYJXJpXcXkwL24kgfY8nHwSmlMxJDOuZIwTvsWYG1PZwZhQ==
 */

// eslint:disable
// tslint:disable

import Products from './products'

interface Barcodes {
  barcode: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: (Date) | null
  /**
   * @default nextval('barcodes_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'barcodes_id'}
  /**
   * @default false
   */
  package: boolean
  product_id: Products['id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at: (Date) | null
  variant_name: (string) | null
}
export default Barcodes;

interface Barcodes_InsertParameters {
  barcode: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: (Date) | null
  /**
   * @default nextval('barcodes_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'barcodes_id'}
  /**
   * @default false
   */
  package?: boolean
  product_id: Products['id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at?: (Date) | null
  variant_name?: (string) | null
}
export type {Barcodes_InsertParameters}
