/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: oxAS8CO9NdSzKNGmKNS+8HJ1Yjm0A1Brmx+NUMr/mAnGekGi1LCSZAw8FdnsI7B/4/0lo68t2iUa/J9Byo77rQ==
 */

// eslint:disable
// tslint:disable

interface Categories {
  created_at: (Date) | null
  /**
   * @default nextval('categories_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'categories_id'}
  name: string
  updated_at: (Date) | null
}
export default Categories;

interface Categories_InsertParameters {
  created_at?: (Date) | null
  /**
   * @default nextval('categories_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'categories_id'}
  name: string
  updated_at?: (Date) | null
}
export type {Categories_InsertParameters}
