/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: oUftL1ZiqQdkJS1h876bqVwZdurnjm179EguDoEWFuUb3lDC2hRSoTXkLRierz+iDMtTwGtHBBBN2qhh/NXoJA==
 */

// eslint:disable
// tslint:disable

import ActiveYears from './active_years'

interface CommitteeMembers {
  active_year_id: ActiveYears['id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: (Date) | null
  description: (string) | null
  favourite_game: (string) | null
  favourite_sugar: (string) | null
  /**
   * @default nextval('committee_members_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'committee_members_id'}
  image: (string) | null
  name: string
  quote: (string) | null
  role: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at: (Date) | null
}
export default CommitteeMembers;

interface CommitteeMembers_InsertParameters {
  active_year_id: ActiveYears['id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: (Date) | null
  description?: (string) | null
  favourite_game?: (string) | null
  favourite_sugar?: (string) | null
  /**
   * @default nextval('committee_members_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'committee_members_id'}
  image?: (string) | null
  name: string
  quote?: (string) | null
  role: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at?: (Date) | null
}
export type {CommitteeMembers_InsertParameters}
