/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tYko6Y2GNVVov4TJN4V2SPb89adCDq3BSwzr4Rf4IiDjnxM3CPmEx58PttteQCzR3YGaotKVcvPoLHqLobbEFw==
 */

// eslint:disable
// tslint:disable

interface DoorStatuses {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: (Date) | null
  /**
   * @default nextval('door_statuses_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'door_statuses_id'}
  status: number
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated: Date
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at: (Date) | null
}
export default DoorStatuses;

interface DoorStatuses_InsertParameters {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: (Date) | null
  /**
   * @default nextval('door_statuses_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'door_statuses_id'}
  status: number
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated?: Date
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at?: (Date) | null
}
export type {DoorStatuses_InsertParameters}
