/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CpQcYpqfg9oS10E71glo24o/5oE3+7m5tYJxT1nTWiwY20H+AolmT6bI12pd0FmbQYcSvM/lHACwjL3s3wkH4Q==
 */

// eslint:disable
// tslint:disable

interface DoorStatuses {
  created_at: (Date) | null
  /**
   * @default nextval('door_statuses_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'door_statuses_id'}
  status: number
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated: Date
  updated_at: (Date) | null
}
export default DoorStatuses;

interface DoorStatuses_InsertParameters {
  created_at?: (Date) | null
  /**
   * @default nextval('door_statuses_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'door_statuses_id'}
  status: number
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated?: Date
  updated_at?: (Date) | null
}
export type {DoorStatuses_InsertParameters}
