/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: c4W5hBd6MtS6cGmVC2moK5jtTMhtNZ2qE5Pz0/ARGqmfBwnDnMIn82Oyvxcj0yhM1ttxAL7prjZps/vGCjKIOQ==
 */

// eslint:disable
// tslint:disable

interface Events {
  created_at: (Date) | null
  date: Date
  description: (string) | null
  facebook_event_link: (string) | null
  google_event_id: (string) | null
  /**
   * @default nextval('events_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'events_id'}
  location: (string) | null
  poster: (string) | null
  /**
   * @default true
   */
  show_on_frontpage: boolean
  title: string
  updated_at: (Date) | null
}
export default Events;

interface Events_InsertParameters {
  created_at?: (Date) | null
  date: Date
  description?: (string) | null
  facebook_event_link?: (string) | null
  google_event_id?: (string) | null
  /**
   * @default nextval('events_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'events_id'}
  location?: (string) | null
  poster?: (string) | null
  /**
   * @default true
   */
  show_on_frontpage?: boolean
  title: string
  updated_at?: (Date) | null
}
export type {Events_InsertParameters}
