/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: U7P1rJ8GTx05T93DRiSM4vrXDIp7ENXUjZwPG7P8rhdcE8xQ3/wV4w/yw5RdgH9lA/XwjJ3wVTWDciYw7O3MSQ==
 */

// eslint:disable
// tslint:disable

interface FailedJobs {
  connection: string
  exception: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  failed_at: Date
  /**
   * @default nextval('failed_jobs_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'failed_jobs_id'}
  payload: string
  queue: string
}
export default FailedJobs;

interface FailedJobs_InsertParameters {
  connection: string
  exception: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  failed_at?: Date
  /**
   * @default nextval('failed_jobs_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'failed_jobs_id'}
  payload: string
  queue: string
}
export type {FailedJobs_InsertParameters}
