/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Y6xn/5bF9WIfkNfNEa1CBQMoswcZB/TbV1bqoaFzFySAiIDNVjW2cABeDWku//w6ZSuPNhnRmeZBz7szZ1a1Lw==
 */

// eslint:disable
// tslint:disable

interface GamePlatforms {
  bgg_type: (string) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: (Date) | null
  /**
   * @default nextval('game_platforms_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'game_platforms_id'}
  name: string
  type: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at: (Date) | null
}
export default GamePlatforms;

interface GamePlatforms_InsertParameters {
  bgg_type?: (string) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: (Date) | null
  /**
   * @default nextval('game_platforms_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'game_platforms_id'}
  name: string
  type: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at?: (Date) | null
}
export type {GamePlatforms_InsertParameters}
