/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8W/l/KOZzRmoPbup/DYPeBkPycM6aIzX4hoHfKgslHy7L5aMoQPYhPoBMxVyPNXyvduC2RgxGmogrxHjLPmZoQ==
 */

// eslint:disable
// tslint:disable

interface GameOwners {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: (Date) | null
  email: (string) | null
  /**
   * @default nextval('game_owners_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'game_owners_id'}
  name: string
  nickname: (string) | null
  phone_number: (string) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at: (Date) | null
}
export default GameOwners;

interface GameOwners_InsertParameters {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: (Date) | null
  email?: (string) | null
  /**
   * @default nextval('game_owners_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'game_owners_id'}
  name: string
  nickname?: (string) | null
  phone_number?: (string) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at?: (Date) | null
}
export type {GameOwners_InsertParameters}
