/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UfgIGrD6OUzM3MKVm8qD2H1o3YbRbw4954YtE8qWBnEHC/4HWxd/YUNyTnCnZgCIeBwYLAzBoJaYSuiaGJ7TZQ==
 */

// eslint:disable
// tslint:disable

interface Games {
  bgg_id: (string) | null
  created_at: (Date) | null
  description: (string) | null
  expansion_to: (number) | null
  game_owner_id: (number) | null
  game_platform_id: number
  /**
   * @default nextval('games_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'games_id'}
  max_players: (number) | null
  max_playtime: (number) | null
  min_players: (number) | null
  min_playtime: (number) | null
  name: string
  published_year: (string) | null
  updated_at: (Date) | null
}
export default Games;

interface Games_InsertParameters {
  bgg_id?: (string) | null
  created_at?: (Date) | null
  description?: (string) | null
  expansion_to?: (number) | null
  game_owner_id?: (number) | null
  game_platform_id: number
  /**
   * @default nextval('games_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'games_id'}
  max_players?: (number) | null
  max_playtime?: (number) | null
  min_players?: (number) | null
  min_playtime?: (number) | null
  name: string
  published_year?: (string) | null
  updated_at?: (Date) | null
}
export type {Games_InsertParameters}
