/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: pps0dwfdMPYrPLnK47X+sQdFUB0Vy7q+QWknicqsb+4M/2Grn5hB4/v0+6YvMQdynFo2wM+MgChPVZ18SpksZw==
 */

// eslint:disable
// tslint:disable

import GameGenre from './game_genre'
import GameOwners from './game_owners'
import GamePlatforms from './game_platforms'

interface Games {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: (Date) | null
  description: (string) | null
  expansion_to: (number) | null
  game_owner_id: (GameOwners['id']) | null
  game_platform_id: GamePlatforms['id']
  genre_id: (GameGenre['id']) | null
  /**
   * @default nextval('games_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'games_id'}
  image_link: (string) | null
  max_players: (number) | null
  max_playtime: (number) | null
  min_players: (number) | null
  min_playtime: (number) | null
  name: string
  published_year: (string) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at: (Date) | null
}
export default Games;

interface Games_InsertParameters {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: (Date) | null
  description?: (string) | null
  expansion_to?: (number) | null
  game_owner_id?: (GameOwners['id']) | null
  game_platform_id: GamePlatforms['id']
  genre_id?: (GameGenre['id']) | null
  /**
   * @default nextval('games_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'games_id'}
  image_link?: (string) | null
  max_players?: (number) | null
  max_playtime?: (number) | null
  min_players?: (number) | null
  min_playtime?: (number) | null
  name: string
  published_year?: (string) | null
  /**
   * @default CURRENT_TIMESTAMP
   */
  updated_at?: (Date) | null
}
export type {Games_InsertParameters}
