/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VXkdz4v+s9K0wqZ3FUrGoZsOsIeLbeBS2HQyK8wYWeQWUsNpQ61itpfeSmidLIS6n1P9mDp8Tehh4DI4yLdmXA==
 */

// eslint:disable
// tslint:disable

interface GameOwners {
  created_at: (Date) | null
  email: (string) | null
  /**
   * @default nextval('game_owners_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'game_owners_id'}
  name: string
  nickname: (string) | null
  phone_number: (string) | null
  updated_at: (Date) | null
}
export default GameOwners;

interface GameOwners_InsertParameters {
  created_at?: (Date) | null
  email?: (string) | null
  /**
   * @default nextval('game_owners_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'game_owners_id'}
  name: string
  nickname?: (string) | null
  phone_number?: (string) | null
  updated_at?: (Date) | null
}
export type {GameOwners_InsertParameters}
