/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: aECgrFSoWUTQP5mizP3gG6VVdNcTgQ3AixvLUUMtftoHG/wLCVKyJ/vKRkHP1Qg3adqSismiBugypTIdBqxCag==
 */

// eslint:disable
// tslint:disable

import Accounts, {Accounts_InsertParameters} from './accounts'
import ActiveYears, {ActiveYears_InsertParameters} from './active_years'
import Barcodes, {Barcodes_InsertParameters} from './barcodes'
import Categories, {Categories_InsertParameters} from './categories'
import CommitteeMembers, {CommitteeMembers_InsertParameters} from './committee_members'
import DoorStatuses, {DoorStatuses_InsertParameters} from './door_statuses'
import Events, {Events_InsertParameters} from './events'
import FailedJobs, {FailedJobs_InsertParameters} from './failed_jobs'
import GameOwners, {GameOwners_InsertParameters} from './game_owners'
import GamePlatforms, {GamePlatforms_InsertParameters} from './game_platforms'
import Games, {Games_InsertParameters} from './games'
import Jobs, {Jobs_InsertParameters} from './jobs'
import Migrations, {Migrations_InsertParameters} from './migrations'
import PasswordResets, {PasswordResets_InsertParameters} from './password_resets'
import Products, {Products_InsertParameters} from './products'
import PurchaseHistories, {PurchaseHistories_InsertParameters} from './purchase_histories'
import PurchaseHistoryProducts, {PurchaseHistoryProducts_InsertParameters} from './purchase_history_products'
import TelescopeEntries, {TelescopeEntries_InsertParameters} from './telescope_entries'
import TelescopeEntriesTags, {TelescopeEntriesTags_InsertParameters} from './telescope_entries_tags'
import TelescopeMonitoring, {TelescopeMonitoring_InsertParameters} from './telescope_monitoring'
import Users, {Users_InsertParameters} from './users'

interface DatabaseSchema {
  accounts: {record: Accounts, insert: Accounts_InsertParameters};
  active_years: {record: ActiveYears, insert: ActiveYears_InsertParameters};
  barcodes: {record: Barcodes, insert: Barcodes_InsertParameters};
  categories: {record: Categories, insert: Categories_InsertParameters};
  committee_members: {record: CommitteeMembers, insert: CommitteeMembers_InsertParameters};
  door_statuses: {record: DoorStatuses, insert: DoorStatuses_InsertParameters};
  events: {record: Events, insert: Events_InsertParameters};
  failed_jobs: {record: FailedJobs, insert: FailedJobs_InsertParameters};
  game_owners: {record: GameOwners, insert: GameOwners_InsertParameters};
  game_platforms: {record: GamePlatforms, insert: GamePlatforms_InsertParameters};
  games: {record: Games, insert: Games_InsertParameters};
  jobs: {record: Jobs, insert: Jobs_InsertParameters};
  migrations: {record: Migrations, insert: Migrations_InsertParameters};
  password_resets: {record: PasswordResets, insert: PasswordResets_InsertParameters};
  products: {record: Products, insert: Products_InsertParameters};
  purchase_histories: {record: PurchaseHistories, insert: PurchaseHistories_InsertParameters};
  purchase_history_products: {record: PurchaseHistoryProducts, insert: PurchaseHistoryProducts_InsertParameters};
  telescope_entries: {record: TelescopeEntries, insert: TelescopeEntries_InsertParameters};
  telescope_entries_tags: {record: TelescopeEntriesTags, insert: TelescopeEntriesTags_InsertParameters};
  telescope_monitoring: {record: TelescopeMonitoring, insert: TelescopeMonitoring_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
