/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: RpqXKc/uK8qYQzjlqTL497+Psgd2L9OPrZkvwI6ujcKovVcMGwTm8DJZLiideU0XihJLil/LGoJB2R0Z4lHHxQ==
 */

// eslint:disable
// tslint:disable

interface Jobs {
  attempts: number
  available_at: number
  created_at: number
  /**
   * @default nextval('jobs_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'jobs_id'}
  payload: string
  queue: string
  reserved_at: (number) | null
}
export default Jobs;

interface Jobs_InsertParameters {
  attempts: number
  available_at: number
  created_at: number
  /**
   * @default nextval('jobs_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'jobs_id'}
  payload: string
  queue: string
  reserved_at?: (number) | null
}
export type {Jobs_InsertParameters}
