/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jQMR7ku2oPUjRfXKWzFWlQz069X9s1ZtoInPjHN9D9VLgUBIllNnL2kPDm7uLsFYWYjIJZHrLE85DQPUhL2C+Q==
 */

// eslint:disable
// tslint:disable

interface PasswordResets {
  created_at: (Date) | null
  email: string
  token: string
}
export default PasswordResets;

interface PasswordResets_InsertParameters {
  created_at?: (Date) | null
  email: string
  token: string
}
export type {PasswordResets_InsertParameters}
