/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ew4c5H4V1awRdT+/zZlFxdLnfeChhPFz6qTvc8yFavofrY33dJ59CGQHpiwpBPqj24ulg+CdmEQI9zOEhs6KYQ==
 */

// eslint:disable
// tslint:disable

interface PasswordResets {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: (Date) | null
  email: string
  token: string
}
export default PasswordResets;

interface PasswordResets_InsertParameters {
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: (Date) | null
  email: string
  token: string
}
export type {PasswordResets_InsertParameters}
