/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Zq6VIjmqFDEGmv7tUgjKEXhAEDzrq0ej/dhl/BQqME4lNBSdag5qGiz08PplWzlfIOteRVzbX5ngGufJ5aVqsw==
 */

// eslint:disable
// tslint:disable

import Categories from './categories'

interface Products {
  /**
   * @default true
   */
  active: boolean
  /**
   * @default 0
   */
  adjustment: number
  category_id: Categories['id']
  created_at: (Date) | null
  /**
   * @default 0
   */
  discount: number
  /**
   * @default nextval('products_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'products_id'}
  name: string
  /**
   * @default 1
   */
  package_size: number
  /**
   * @default false
   */
  pant: boolean
  price: number
  purchase_price: number
  updated_at: (Date) | null
}
export default Products;

interface Products_InsertParameters {
  /**
   * @default true
   */
  active?: boolean
  /**
   * @default 0
   */
  adjustment?: number
  category_id: Categories['id']
  created_at?: (Date) | null
  /**
   * @default 0
   */
  discount?: number
  /**
   * @default nextval('products_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'products_id'}
  name: string
  /**
   * @default 1
   */
  package_size?: number
  /**
   * @default false
   */
  pant?: boolean
  price: number
  purchase_price: number
  updated_at?: (Date) | null
}
export type {Products_InsertParameters}
