/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: E3GQrOoVW3EwltJS8fVvZNssZ+SnaO44VbYXPzandr/6IfZQewbNW5nkud3mmJQCCHtcUXsSdeaV7p5HmwBcAA==
 */

// eslint:disable
// tslint:disable

import PurchaseHistories from './purchase_histories'

interface PurchaseHistoryProducts {
  created_at: (Date) | null
  /**
   * @default nextval('purchase_history_products_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'purchase_history_products_id'}
  name: string
  price: number
  purchase_history_id: PurchaseHistories['id']
  updated_at: (Date) | null
}
export default PurchaseHistoryProducts;

interface PurchaseHistoryProducts_InsertParameters {
  created_at?: (Date) | null
  /**
   * @default nextval('purchase_history_products_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'purchase_history_products_id'}
  name: string
  price: number
  purchase_history_id: PurchaseHistories['id']
  updated_at?: (Date) | null
}
export type {PurchaseHistoryProducts_InsertParameters}
