/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FRN5ebHmlm4EMCSFCVpxpqAp3q2JHCZRnR3IoD9/fVI4wTtOBeD6/4uwkffluZBHrZ7/A6vlRKPFi03KU7yP7A==
 */

// eslint:disable
// tslint:disable

interface TelescopeEntries {
  batch_id: string
  content: string
  created_at: (Date) | null
  family_hash: (string) | null
  /**
   * @default nextval('telescope_entries_sequence_seq'::regclass)
   */
  sequence: number & {readonly __brand?: 'telescope_entries_sequence'}
  /**
   * @default true
   */
  should_display_on_index: boolean
  type: string
  uuid: string
}
export default TelescopeEntries;

interface TelescopeEntries_InsertParameters {
  batch_id: string
  content: string
  created_at?: (Date) | null
  family_hash?: (string) | null
  /**
   * @default nextval('telescope_entries_sequence_seq'::regclass)
   */
  sequence?: number & {readonly __brand?: 'telescope_entries_sequence'}
  /**
   * @default true
   */
  should_display_on_index?: boolean
  type: string
  uuid: string
}
export type {TelescopeEntries_InsertParameters}
