/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 64bVlDEW57MHfOgA/lYdZQ8y3bGZwfzMY2UsI6Lzzirt38NIxwhIa6yK8HRJCbJVmpvdBrK0cz0zf7cwnpH0oA==
 */

// eslint:disable
// tslint:disable

interface TelescopeMonitoring {
  tag: string
}
export default TelescopeMonitoring;

interface TelescopeMonitoring_InsertParameters {
  tag: string
}
export type {TelescopeMonitoring_InsertParameters}
