/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tfhz28hqECTUEmH2FW+GrHxEmU51JzPqgBJ/sQvVyreygoKnM6wdwHQjW1vxndNbl+jb9uUj7KHATuG/y0dLvA==
 */

// eslint:disable
// tslint:disable

interface TelescopeEntries {
  batch_id: string
  content: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at: (Date) | null
  family_hash: (string) | null
  /**
   * @default nextval('telescope_entries_sequence_seq'::regclass)
   */
  sequence: number & {readonly __brand?: 'telescope_entries_sequence'}
  /**
   * @default true
   */
  should_display_on_index: boolean
  type: string
  uuid: string
}
export default TelescopeEntries;

interface TelescopeEntries_InsertParameters {
  batch_id: string
  content: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  created_at?: (Date) | null
  family_hash?: (string) | null
  /**
   * @default nextval('telescope_entries_sequence_seq'::regclass)
   */
  sequence?: number & {readonly __brand?: 'telescope_entries_sequence'}
  /**
   * @default true
   */
  should_display_on_index?: boolean
  type: string
  uuid: string
}
export type {TelescopeEntries_InsertParameters}
