/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ik6QI48/U/jakBw2Q2CQaTL1goT15zLiPeHvHbx99/BFqfemZ6CpjZBrXJoj+rZdZS2ci8Y4aE65+x7fCPaDkA==
 */

// eslint:disable
// tslint:disable

import TelescopeEntries from './telescope_entries'

interface TelescopeEntriesTags {
  entry_uuid: TelescopeEntries['uuid']
  tag: string
}
export default TelescopeEntriesTags;

interface TelescopeEntriesTags_InsertParameters {
  entry_uuid: TelescopeEntries['uuid']
  tag: string
}
export type {TelescopeEntriesTags_InsertParameters}
