/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: U1USC67RTgXFY3iRMNtc/B2YHSDCAH/k45Hd8bp+mSt0rOcHa6lcJwGyuep18epIxDuzlV8PkyuqMFxGPSiksA==
 */

// eslint:disable
// tslint:disable

interface Users {
  api_token: (string) | null
  created_at: (Date) | null
  email: string
  email_verified_at: (Date) | null
  /**
   * @default nextval('users_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'users_id'}
  name: string
  password: string
  remember_token: (string) | null
  updated_at: (Date) | null
}
export default Users;

interface Users_InsertParameters {
  api_token?: (string) | null
  created_at?: (Date) | null
  email: string
  email_verified_at?: (Date) | null
  /**
   * @default nextval('users_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'users_id'}
  name: string
  password: string
  remember_token?: (string) | null
  updated_at?: (Date) | null
}
export type {Users_InsertParameters}
