# Sample workflow for building and deploying a Nuxt site to GitHub Pages
#
# To get started with Nuxt see: https://nuxtjs.org/docs/get-started/installation
#
name: Build docker image

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  attestations: write
  packages: write

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    concurrency:
      group: hd-web
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            web/.output
            web/.nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('web/.output') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: web
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/hd-chalmers/hd-web:latest
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/hd-chalmers/hd-web
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: false
          
  # Build job
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: "16"
#          cache: ${{ steps.detect-package-manager.outputs.manager }}
#      - name: Setup Pages
#        uses: actions/configure-pages@v4
#        with:
          # Automatically inject router.base in your Nuxt configuration file and set
          # target to static (https://nuxtjs.org/docs/configuration-glossary/configuration-target/).
          #
          # You may remove this line if you want to manage the configuration yourself.
#          static_site_generator: nuxt
#      - name: Restore cache
#        uses: actions/cache@v3
#        with:
#          path: |
#            web/.output
#            web/.nuxt
#          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('web/.output') }}
#          restore-keys: |
#            ${{ runner.os }}-nuxt-build-
#      - name: Install dependencies
#        run: yarn install
#        working-directory: ./web
#      - name: Static HTML export with Nuxt
#        run: yarn generate
#        working-directory: ./web
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: ./web/.output/public

  # Deployment job
#  deploy-pages:
#    name: Deploy to Github Pages
#    concurrency:
#      group: pages
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4

